[project]
name = "cms-public-data-catalog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-core>=1.11.3",
    "dbt-duckdb>=1.10.0",
    "requests>=2.32.0",
]
